# permissions for end users to edit mywebapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mywebapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-src
    app.kubernetes.io/part-of: operator-src
    app.kubernetes.io/managed-by: kustomize
  name: mywebapp-editor-role
rules:
- apiGroups:
  - web-app.4m.fyi
  resources:
  - mywebapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web-app.4m.fyi
  resources:
  - mywebapps/status
  verbs:
  - get
