apiVersion: web-app.4m.fyi/v1
kind: MyWebApp
metadata:
  labels:
    app.kubernetes.io/name: mywebapp
    app.kubernetes.io/instance: mywebapp-sample
    app.kubernetes.io/part-of: operator-src
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-src
  name: mywebapp-sample
spec:
  # TODO(user): Add fields here
